/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as DocProbeRouteImport } from './routes/doc-probe'
import { Route as CanvasProbeRouteImport } from './routes/canvas-probe'
import { Route as CanvasDemoRouteImport } from './routes/canvas-demo'
import { Route as BusyRouteImport } from './routes/busy'
import { Route as BrandProbeRouteImport } from './routes/brand-probe'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetupIndexRouteImport } from './routes/setup.index'
import { Route as ProspeccionIndexRouteImport } from './routes/prospeccion.index'
import { Route as T3SplatRouteImport } from './routes/t3.$'
import { Route as RoomSlugRouteImport } from './routes/room.$slug'
import { Route as ProspeccionIdRouteImport } from './routes/prospeccion.$id'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as CoeditarSlugRouteImport } from './routes/coeditar.$slug'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as ArtefactoIdRouteImport } from './routes/artefacto.$id'
import { Route as ApiWarmRouteImport } from './routes/api.warm'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as ApiTtsWarmRouteImport } from './routes/api.tts-warm'
import { Route as ApiStreamRouteImport } from './routes/api.stream'
import { Route as ApiManifestRouteImport } from './routes/api.manifest'
import { Route as ApiEventStreamRouteImport } from './routes/api.event-stream'
import { Route as ApiBrandLogoRouteImport } from './routes/api.brand-logo'
import { Route as ApiBrandCssRouteImport } from './routes/api.brand-css'
import { Route as ApiAgentAssetRouteImport } from './routes/api.agent-asset'
import { Route as SetupEasybitsConnectRouteImport } from './routes/setup.easybits.connect'
import { Route as SetupEasybitsCallbackRouteImport } from './routes/setup.easybits.callback'
import { Route as SetupProviderConnectRouteImport } from './routes/setup.$provider.connect'
import { Route as SetupProviderCallbackRouteImport } from './routes/setup.$provider.callback'
import { Route as OauthProviderCallbackRouteImport } from './routes/oauth.$provider.callback'
import { Route as CoeditarInvitacionTokenRouteImport } from './routes/coeditar.invitacion.$token'
import { Route as ArtefactoIdRawRouteImport } from './routes/artefacto.$id.raw'
import { Route as ApiProspeccionAgentRouteImport } from './routes/api.prospeccion.agent'
import { Route as ApiInternalMembersRouteImport } from './routes/api.internal.members'
import { Route as ApiInternalAnnouncementsRouteImport } from './routes/api.internal.announcements'
import { Route as ApiFormTokenRouteImport } from './routes/api.form.$token'
import { Route as ApiFormUploadTokenRouteImport } from './routes/api.form-upload.$token'
import { Route as ApiFormFileIdRouteImport } from './routes/api.form-file.$id'
import { Route as ApiFormDraftTokenRouteImport } from './routes/api.form-draft.$token'
import { Route as ApiDocXlsxIdRouteImport } from './routes/api.doc-xlsx.$id'
import { Route as ApiDocTtsIdRouteImport } from './routes/api.doc-tts.$id'
import { Route as ApiDocPdfIdRouteImport } from './routes/api.doc-pdf.$id'
import { Route as ApiDocDocxIdRouteImport } from './routes/api.doc-docx.$id'
import { Route as ApiDocCheckIdRouteImport } from './routes/api.doc-check.$id'
import { Route as ApiDevDriveRouteImport } from './routes/api.dev.drive'
import { Route as ApiConnectorsToolsRouteImport } from './routes/api.connectors.tools'
import { Route as ApiBrandAssetSplatRouteImport } from './routes/api.brand-asset.$'
import { Route as ApiAttachmentIdRouteImport } from './routes/api.attachment.$id'
import { Route as ApiArtifactStreamIdRouteImport } from './routes/api.artifact-stream.$id'
import { Route as RoomSlugTranscripcionIdRouteImport } from './routes/room.$slug_.transcripcion.$id'
import { Route as ApiWhatsappConnectStartRouteImport } from './routes/api.whatsapp.connect.start'
import { Route as ApiWhatsappConnectFinishRouteImport } from './routes/api.whatsapp.connect.finish'
import { Route as ApiPUTokenRouteImport } from './routes/api.p.u.$token'
import { Route as ApiPOTokenRouteImport } from './routes/api.p.o.$token'
import { Route as ApiPCTokenRouteImport } from './routes/api.p.c.$token'
import { Route as ApiHooksSentryTokenRouteImport } from './routes/api.hooks.sentry.$token'
import { Route as ApiCollabDocIdStateRouteImport } from './routes/api.collab.$docId.state'
import { Route as ApiCollabDocIdSessionEndRouteImport } from './routes/api.collab.$docId.session-end'
import { Route as ApiHooksWhatsappTokenMessageRouteImport } from './routes/api.hooks.whatsapp.$token.message'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const DocProbeRoute = DocProbeRouteImport.update({
  id: '/doc-probe',
  path: '/doc-probe',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasProbeRoute = CanvasProbeRouteImport.update({
  id: '/canvas-probe',
  path: '/canvas-probe',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasDemoRoute = CanvasDemoRouteImport.update({
  id: '/canvas-demo',
  path: '/canvas-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const BusyRoute = BusyRouteImport.update({
  id: '/busy',
  path: '/busy',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandProbeRoute = BrandProbeRouteImport.update({
  id: '/brand-probe',
  path: '/brand-probe',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetupRoute,
} as any)
const ProspeccionIndexRoute = ProspeccionIndexRouteImport.update({
  id: '/prospeccion/',
  path: '/prospeccion/',
  getParentRoute: () => rootRouteImport,
} as any)
const T3SplatRoute = T3SplatRouteImport.update({
  id: '/t3/$',
  path: '/t3/$',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomSlugRoute = RoomSlugRouteImport.update({
  id: '/room/$slug',
  path: '/room/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspeccionIdRoute = ProspeccionIdRouteImport.update({
  id: '/prospeccion/$id',
  path: '/prospeccion/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CoeditarSlugRoute = CoeditarSlugRouteImport.update({
  id: '/coeditar/$slug',
  path: '/coeditar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtefactoIdRoute = ArtefactoIdRouteImport.update({
  id: '/artefacto/$id',
  path: '/artefacto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWarmRoute = ApiWarmRouteImport.update({
  id: '/api/warm',
  path: '/api/warm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsWarmRoute = ApiTtsWarmRouteImport.update({
  id: '/api/tts-warm',
  path: '/api/tts-warm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManifestRoute = ApiManifestRouteImport.update({
  id: '/api/manifest',
  path: '/api/manifest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventStreamRoute = ApiEventStreamRouteImport.update({
  id: '/api/event-stream',
  path: '/api/event-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandLogoRoute = ApiBrandLogoRouteImport.update({
  id: '/api/brand-logo',
  path: '/api/brand-logo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandCssRoute = ApiBrandCssRouteImport.update({
  id: '/api/brand-css',
  path: '/api/brand-css',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentAssetRoute = ApiAgentAssetRouteImport.update({
  id: '/api/agent-asset',
  path: '/api/agent-asset',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupEasybitsConnectRoute = SetupEasybitsConnectRouteImport.update({
  id: '/easybits/connect',
  path: '/easybits/connect',
  getParentRoute: () => SetupRoute,
} as any)
const SetupEasybitsCallbackRoute = SetupEasybitsCallbackRouteImport.update({
  id: '/easybits/callback',
  path: '/easybits/callback',
  getParentRoute: () => SetupRoute,
} as any)
const SetupProviderConnectRoute = SetupProviderConnectRouteImport.update({
  id: '/$provider/connect',
  path: '/$provider/connect',
  getParentRoute: () => SetupRoute,
} as any)
const SetupProviderCallbackRoute = SetupProviderCallbackRouteImport.update({
  id: '/$provider/callback',
  path: '/$provider/callback',
  getParentRoute: () => SetupRoute,
} as any)
const OauthProviderCallbackRoute = OauthProviderCallbackRouteImport.update({
  id: '/oauth/$provider/callback',
  path: '/oauth/$provider/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CoeditarInvitacionTokenRoute = CoeditarInvitacionTokenRouteImport.update({
  id: '/coeditar/invitacion/$token',
  path: '/coeditar/invitacion/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtefactoIdRawRoute = ArtefactoIdRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => ArtefactoIdRoute,
} as any)
const ApiProspeccionAgentRoute = ApiProspeccionAgentRouteImport.update({
  id: '/api/prospeccion/agent',
  path: '/api/prospeccion/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalMembersRoute = ApiInternalMembersRouteImport.update({
  id: '/api/internal/members',
  path: '/api/internal/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalAnnouncementsRoute =
  ApiInternalAnnouncementsRouteImport.update({
    id: '/api/internal/announcements',
    path: '/api/internal/announcements',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFormTokenRoute = ApiFormTokenRouteImport.update({
  id: '/api/form/$token',
  path: '/api/form/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormUploadTokenRoute = ApiFormUploadTokenRouteImport.update({
  id: '/api/form-upload/$token',
  path: '/api/form-upload/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormFileIdRoute = ApiFormFileIdRouteImport.update({
  id: '/api/form-file/$id',
  path: '/api/form-file/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFormDraftTokenRoute = ApiFormDraftTokenRouteImport.update({
  id: '/api/form-draft/$token',
  path: '/api/form-draft/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocXlsxIdRoute = ApiDocXlsxIdRouteImport.update({
  id: '/api/doc-xlsx/$id',
  path: '/api/doc-xlsx/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocTtsIdRoute = ApiDocTtsIdRouteImport.update({
  id: '/api/doc-tts/$id',
  path: '/api/doc-tts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocPdfIdRoute = ApiDocPdfIdRouteImport.update({
  id: '/api/doc-pdf/$id',
  path: '/api/doc-pdf/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocDocxIdRoute = ApiDocDocxIdRouteImport.update({
  id: '/api/doc-docx/$id',
  path: '/api/doc-docx/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocCheckIdRoute = ApiDocCheckIdRouteImport.update({
  id: '/api/doc-check/$id',
  path: '/api/doc-check/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevDriveRoute = ApiDevDriveRouteImport.update({
  id: '/api/dev/drive',
  path: '/api/dev/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConnectorsToolsRoute = ApiConnectorsToolsRouteImport.update({
  id: '/api/connectors/tools',
  path: '/api/connectors/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandAssetSplatRoute = ApiBrandAssetSplatRouteImport.update({
  id: '/api/brand-asset/$',
  path: '/api/brand-asset/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttachmentIdRoute = ApiAttachmentIdRouteImport.update({
  id: '/api/attachment/$id',
  path: '/api/attachment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtifactStreamIdRoute = ApiArtifactStreamIdRouteImport.update({
  id: '/api/artifact-stream/$id',
  path: '/api/artifact-stream/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomSlugTranscripcionIdRoute = RoomSlugTranscripcionIdRouteImport.update({
  id: '/room/$slug_/transcripcion/$id',
  path: '/room/$slug/transcripcion/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappConnectStartRoute = ApiWhatsappConnectStartRouteImport.update({
  id: '/api/whatsapp/connect/start',
  path: '/api/whatsapp/connect/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappConnectFinishRoute =
  ApiWhatsappConnectFinishRouteImport.update({
    id: '/api/whatsapp/connect/finish',
    path: '/api/whatsapp/connect/finish',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPUTokenRoute = ApiPUTokenRouteImport.update({
  id: '/api/p/u/$token',
  path: '/api/p/u/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPOTokenRoute = ApiPOTokenRouteImport.update({
  id: '/api/p/o/$token',
  path: '/api/p/o/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPCTokenRoute = ApiPCTokenRouteImport.update({
  id: '/api/p/c/$token',
  path: '/api/p/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHooksSentryTokenRoute = ApiHooksSentryTokenRouteImport.update({
  id: '/api/hooks/sentry/$token',
  path: '/api/hooks/sentry/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCollabDocIdStateRoute = ApiCollabDocIdStateRouteImport.update({
  id: '/api/collab/$docId/state',
  path: '/api/collab/$docId/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCollabDocIdSessionEndRoute =
  ApiCollabDocIdSessionEndRouteImport.update({
    id: '/api/collab/$docId/session-end',
    path: '/api/collab/$docId/session-end',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHooksWhatsappTokenMessageRoute =
  ApiHooksWhatsappTokenMessageRouteImport.update({
    id: '/api/hooks/whatsapp/$token/message',
    path: '/api/hooks/whatsapp/$token/message',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/brand-probe': typeof BrandProbeRoute
  '/busy': typeof BusyRoute
  '/canvas-demo': typeof CanvasDemoRoute
  '/canvas-probe': typeof CanvasProbeRoute
  '/doc-probe': typeof DocProbeRoute
  '/forms': typeof FormsRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/setup': typeof SetupRouteWithChildren
  '/api/agent-asset': typeof ApiAgentAssetRoute
  '/api/brand-css': typeof ApiBrandCssRoute
  '/api/brand-logo': typeof ApiBrandLogoRoute
  '/api/event-stream': typeof ApiEventStreamRoute
  '/api/manifest': typeof ApiManifestRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/tts-warm': typeof ApiTtsWarmRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/warm': typeof ApiWarmRoute
  '/artefacto/$id': typeof ArtefactoIdRouteWithChildren
  '/c/$slug': typeof CSlugRoute
  '/coeditar/$slug': typeof CoeditarSlugRoute
  '/join/$token': typeof JoinTokenRoute
  '/prospeccion/$id': typeof ProspeccionIdRoute
  '/room/$slug': typeof RoomSlugRoute
  '/t3/$': typeof T3SplatRoute
  '/prospeccion/': typeof ProspeccionIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/api/artifact-stream/$id': typeof ApiArtifactStreamIdRoute
  '/api/attachment/$id': typeof ApiAttachmentIdRoute
  '/api/brand-asset/$': typeof ApiBrandAssetSplatRoute
  '/api/connectors/tools': typeof ApiConnectorsToolsRoute
  '/api/dev/drive': typeof ApiDevDriveRoute
  '/api/doc-check/$id': typeof ApiDocCheckIdRoute
  '/api/doc-docx/$id': typeof ApiDocDocxIdRoute
  '/api/doc-pdf/$id': typeof ApiDocPdfIdRoute
  '/api/doc-tts/$id': typeof ApiDocTtsIdRoute
  '/api/doc-xlsx/$id': typeof ApiDocXlsxIdRoute
  '/api/form-draft/$token': typeof ApiFormDraftTokenRoute
  '/api/form-file/$id': typeof ApiFormFileIdRoute
  '/api/form-upload/$token': typeof ApiFormUploadTokenRoute
  '/api/form/$token': typeof ApiFormTokenRoute
  '/api/internal/announcements': typeof ApiInternalAnnouncementsRoute
  '/api/internal/members': typeof ApiInternalMembersRoute
  '/api/prospeccion/agent': typeof ApiProspeccionAgentRoute
  '/artefacto/$id/raw': typeof ArtefactoIdRawRoute
  '/coeditar/invitacion/$token': typeof CoeditarInvitacionTokenRoute
  '/oauth/$provider/callback': typeof OauthProviderCallbackRoute
  '/setup/$provider/callback': typeof SetupProviderCallbackRoute
  '/setup/$provider/connect': typeof SetupProviderConnectRoute
  '/setup/easybits/callback': typeof SetupEasybitsCallbackRoute
  '/setup/easybits/connect': typeof SetupEasybitsConnectRoute
  '/api/collab/$docId/session-end': typeof ApiCollabDocIdSessionEndRoute
  '/api/collab/$docId/state': typeof ApiCollabDocIdStateRoute
  '/api/hooks/sentry/$token': typeof ApiHooksSentryTokenRoute
  '/api/p/c/$token': typeof ApiPCTokenRoute
  '/api/p/o/$token': typeof ApiPOTokenRoute
  '/api/p/u/$token': typeof ApiPUTokenRoute
  '/api/whatsapp/connect/finish': typeof ApiWhatsappConnectFinishRoute
  '/api/whatsapp/connect/start': typeof ApiWhatsappConnectStartRoute
  '/room/$slug/transcripcion/$id': typeof RoomSlugTranscripcionIdRoute
  '/api/hooks/whatsapp/$token/message': typeof ApiHooksWhatsappTokenMessageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/brand-probe': typeof BrandProbeRoute
  '/busy': typeof BusyRoute
  '/canvas-demo': typeof CanvasDemoRoute
  '/canvas-probe': typeof CanvasProbeRoute
  '/doc-probe': typeof DocProbeRoute
  '/forms': typeof FormsRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/api/agent-asset': typeof ApiAgentAssetRoute
  '/api/brand-css': typeof ApiBrandCssRoute
  '/api/brand-logo': typeof ApiBrandLogoRoute
  '/api/event-stream': typeof ApiEventStreamRoute
  '/api/manifest': typeof ApiManifestRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/tts-warm': typeof ApiTtsWarmRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/warm': typeof ApiWarmRoute
  '/artefacto/$id': typeof ArtefactoIdRouteWithChildren
  '/c/$slug': typeof CSlugRoute
  '/coeditar/$slug': typeof CoeditarSlugRoute
  '/join/$token': typeof JoinTokenRoute
  '/prospeccion/$id': typeof ProspeccionIdRoute
  '/room/$slug': typeof RoomSlugRoute
  '/t3/$': typeof T3SplatRoute
  '/prospeccion': typeof ProspeccionIndexRoute
  '/setup': typeof SetupIndexRoute
  '/api/artifact-stream/$id': typeof ApiArtifactStreamIdRoute
  '/api/attachment/$id': typeof ApiAttachmentIdRoute
  '/api/brand-asset/$': typeof ApiBrandAssetSplatRoute
  '/api/connectors/tools': typeof ApiConnectorsToolsRoute
  '/api/dev/drive': typeof ApiDevDriveRoute
  '/api/doc-check/$id': typeof ApiDocCheckIdRoute
  '/api/doc-docx/$id': typeof ApiDocDocxIdRoute
  '/api/doc-pdf/$id': typeof ApiDocPdfIdRoute
  '/api/doc-tts/$id': typeof ApiDocTtsIdRoute
  '/api/doc-xlsx/$id': typeof ApiDocXlsxIdRoute
  '/api/form-draft/$token': typeof ApiFormDraftTokenRoute
  '/api/form-file/$id': typeof ApiFormFileIdRoute
  '/api/form-upload/$token': typeof ApiFormUploadTokenRoute
  '/api/form/$token': typeof ApiFormTokenRoute
  '/api/internal/announcements': typeof ApiInternalAnnouncementsRoute
  '/api/internal/members': typeof ApiInternalMembersRoute
  '/api/prospeccion/agent': typeof ApiProspeccionAgentRoute
  '/artefacto/$id/raw': typeof ArtefactoIdRawRoute
  '/coeditar/invitacion/$token': typeof CoeditarInvitacionTokenRoute
  '/oauth/$provider/callback': typeof OauthProviderCallbackRoute
  '/setup/$provider/callback': typeof SetupProviderCallbackRoute
  '/setup/$provider/connect': typeof SetupProviderConnectRoute
  '/setup/easybits/callback': typeof SetupEasybitsCallbackRoute
  '/setup/easybits/connect': typeof SetupEasybitsConnectRoute
  '/api/collab/$docId/session-end': typeof ApiCollabDocIdSessionEndRoute
  '/api/collab/$docId/state': typeof ApiCollabDocIdStateRoute
  '/api/hooks/sentry/$token': typeof ApiHooksSentryTokenRoute
  '/api/p/c/$token': typeof ApiPCTokenRoute
  '/api/p/o/$token': typeof ApiPOTokenRoute
  '/api/p/u/$token': typeof ApiPUTokenRoute
  '/api/whatsapp/connect/finish': typeof ApiWhatsappConnectFinishRoute
  '/api/whatsapp/connect/start': typeof ApiWhatsappConnectStartRoute
  '/room/$slug/transcripcion/$id': typeof RoomSlugTranscripcionIdRoute
  '/api/hooks/whatsapp/$token/message': typeof ApiHooksWhatsappTokenMessageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/brand-probe': typeof BrandProbeRoute
  '/busy': typeof BusyRoute
  '/canvas-demo': typeof CanvasDemoRoute
  '/canvas-probe': typeof CanvasProbeRoute
  '/doc-probe': typeof DocProbeRoute
  '/forms': typeof FormsRoute
  '/login': typeof LoginRoute
  '/memory': typeof MemoryRoute
  '/setup': typeof SetupRouteWithChildren
  '/api/agent-asset': typeof ApiAgentAssetRoute
  '/api/brand-css': typeof ApiBrandCssRoute
  '/api/brand-logo': typeof ApiBrandLogoRoute
  '/api/event-stream': typeof ApiEventStreamRoute
  '/api/manifest': typeof ApiManifestRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/tts-warm': typeof ApiTtsWarmRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/warm': typeof ApiWarmRoute
  '/artefacto/$id': typeof ArtefactoIdRouteWithChildren
  '/c/$slug': typeof CSlugRoute
  '/coeditar/$slug': typeof CoeditarSlugRoute
  '/join/$token': typeof JoinTokenRoute
  '/prospeccion/$id': typeof ProspeccionIdRoute
  '/room/$slug': typeof RoomSlugRoute
  '/t3/$': typeof T3SplatRoute
  '/prospeccion/': typeof ProspeccionIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/api/artifact-stream/$id': typeof ApiArtifactStreamIdRoute
  '/api/attachment/$id': typeof ApiAttachmentIdRoute
  '/api/brand-asset/$': typeof ApiBrandAssetSplatRoute
  '/api/connectors/tools': typeof ApiConnectorsToolsRoute
  '/api/dev/drive': typeof ApiDevDriveRoute
  '/api/doc-check/$id': typeof ApiDocCheckIdRoute
  '/api/doc-docx/$id': typeof ApiDocDocxIdRoute
  '/api/doc-pdf/$id': typeof ApiDocPdfIdRoute
  '/api/doc-tts/$id': typeof ApiDocTtsIdRoute
  '/api/doc-xlsx/$id': typeof ApiDocXlsxIdRoute
  '/api/form-draft/$token': typeof ApiFormDraftTokenRoute
  '/api/form-file/$id': typeof ApiFormFileIdRoute
  '/api/form-upload/$token': typeof ApiFormUploadTokenRoute
  '/api/form/$token': typeof ApiFormTokenRoute
  '/api/internal/announcements': typeof ApiInternalAnnouncementsRoute
  '/api/internal/members': typeof ApiInternalMembersRoute
  '/api/prospeccion/agent': typeof ApiProspeccionAgentRoute
  '/artefacto/$id/raw': typeof ArtefactoIdRawRoute
  '/coeditar/invitacion/$token': typeof CoeditarInvitacionTokenRoute
  '/oauth/$provider/callback': typeof OauthProviderCallbackRoute
  '/setup/$provider/callback': typeof SetupProviderCallbackRoute
  '/setup/$provider/connect': typeof SetupProviderConnectRoute
  '/setup/easybits/callback': typeof SetupEasybitsCallbackRoute
  '/setup/easybits/connect': typeof SetupEasybitsConnectRoute
  '/api/collab/$docId/session-end': typeof ApiCollabDocIdSessionEndRoute
  '/api/collab/$docId/state': typeof ApiCollabDocIdStateRoute
  '/api/hooks/sentry/$token': typeof ApiHooksSentryTokenRoute
  '/api/p/c/$token': typeof ApiPCTokenRoute
  '/api/p/o/$token': typeof ApiPOTokenRoute
  '/api/p/u/$token': typeof ApiPUTokenRoute
  '/api/whatsapp/connect/finish': typeof ApiWhatsappConnectFinishRoute
  '/api/whatsapp/connect/start': typeof ApiWhatsappConnectStartRoute
  '/room/$slug_/transcripcion/$id': typeof RoomSlugTranscripcionIdRoute
  '/api/hooks/whatsapp/$token/message': typeof ApiHooksWhatsappTokenMessageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artifacts'
    | '/brand-probe'
    | '/busy'
    | '/canvas-demo'
    | '/canvas-probe'
    | '/doc-probe'
    | '/forms'
    | '/login'
    | '/memory'
    | '/setup'
    | '/api/agent-asset'
    | '/api/brand-css'
    | '/api/brand-logo'
    | '/api/event-stream'
    | '/api/manifest'
    | '/api/stream'
    | '/api/tts-warm'
    | '/api/upload'
    | '/api/warm'
    | '/artefacto/$id'
    | '/c/$slug'
    | '/coeditar/$slug'
    | '/join/$token'
    | '/prospeccion/$id'
    | '/room/$slug'
    | '/t3/$'
    | '/prospeccion/'
    | '/setup/'
    | '/api/artifact-stream/$id'
    | '/api/attachment/$id'
    | '/api/brand-asset/$'
    | '/api/connectors/tools'
    | '/api/dev/drive'
    | '/api/doc-check/$id'
    | '/api/doc-docx/$id'
    | '/api/doc-pdf/$id'
    | '/api/doc-tts/$id'
    | '/api/doc-xlsx/$id'
    | '/api/form-draft/$token'
    | '/api/form-file/$id'
    | '/api/form-upload/$token'
    | '/api/form/$token'
    | '/api/internal/announcements'
    | '/api/internal/members'
    | '/api/prospeccion/agent'
    | '/artefacto/$id/raw'
    | '/coeditar/invitacion/$token'
    | '/oauth/$provider/callback'
    | '/setup/$provider/callback'
    | '/setup/$provider/connect'
    | '/setup/easybits/callback'
    | '/setup/easybits/connect'
    | '/api/collab/$docId/session-end'
    | '/api/collab/$docId/state'
    | '/api/hooks/sentry/$token'
    | '/api/p/c/$token'
    | '/api/p/o/$token'
    | '/api/p/u/$token'
    | '/api/whatsapp/connect/finish'
    | '/api/whatsapp/connect/start'
    | '/room/$slug/transcripcion/$id'
    | '/api/hooks/whatsapp/$token/message'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artifacts'
    | '/brand-probe'
    | '/busy'
    | '/canvas-demo'
    | '/canvas-probe'
    | '/doc-probe'
    | '/forms'
    | '/login'
    | '/memory'
    | '/api/agent-asset'
    | '/api/brand-css'
    | '/api/brand-logo'
    | '/api/event-stream'
    | '/api/manifest'
    | '/api/stream'
    | '/api/tts-warm'
    | '/api/upload'
    | '/api/warm'
    | '/artefacto/$id'
    | '/c/$slug'
    | '/coeditar/$slug'
    | '/join/$token'
    | '/prospeccion/$id'
    | '/room/$slug'
    | '/t3/$'
    | '/prospeccion'
    | '/setup'
    | '/api/artifact-stream/$id'
    | '/api/attachment/$id'
    | '/api/brand-asset/$'
    | '/api/connectors/tools'
    | '/api/dev/drive'
    | '/api/doc-check/$id'
    | '/api/doc-docx/$id'
    | '/api/doc-pdf/$id'
    | '/api/doc-tts/$id'
    | '/api/doc-xlsx/$id'
    | '/api/form-draft/$token'
    | '/api/form-file/$id'
    | '/api/form-upload/$token'
    | '/api/form/$token'
    | '/api/internal/announcements'
    | '/api/internal/members'
    | '/api/prospeccion/agent'
    | '/artefacto/$id/raw'
    | '/coeditar/invitacion/$token'
    | '/oauth/$provider/callback'
    | '/setup/$provider/callback'
    | '/setup/$provider/connect'
    | '/setup/easybits/callback'
    | '/setup/easybits/connect'
    | '/api/collab/$docId/session-end'
    | '/api/collab/$docId/state'
    | '/api/hooks/sentry/$token'
    | '/api/p/c/$token'
    | '/api/p/o/$token'
    | '/api/p/u/$token'
    | '/api/whatsapp/connect/finish'
    | '/api/whatsapp/connect/start'
    | '/room/$slug/transcripcion/$id'
    | '/api/hooks/whatsapp/$token/message'
  id:
    | '__root__'
    | '/'
    | '/artifacts'
    | '/brand-probe'
    | '/busy'
    | '/canvas-demo'
    | '/canvas-probe'
    | '/doc-probe'
    | '/forms'
    | '/login'
    | '/memory'
    | '/setup'
    | '/api/agent-asset'
    | '/api/brand-css'
    | '/api/brand-logo'
    | '/api/event-stream'
    | '/api/manifest'
    | '/api/stream'
    | '/api/tts-warm'
    | '/api/upload'
    | '/api/warm'
    | '/artefacto/$id'
    | '/c/$slug'
    | '/coeditar/$slug'
    | '/join/$token'
    | '/prospeccion/$id'
    | '/room/$slug'
    | '/t3/$'
    | '/prospeccion/'
    | '/setup/'
    | '/api/artifact-stream/$id'
    | '/api/attachment/$id'
    | '/api/brand-asset/$'
    | '/api/connectors/tools'
    | '/api/dev/drive'
    | '/api/doc-check/$id'
    | '/api/doc-docx/$id'
    | '/api/doc-pdf/$id'
    | '/api/doc-tts/$id'
    | '/api/doc-xlsx/$id'
    | '/api/form-draft/$token'
    | '/api/form-file/$id'
    | '/api/form-upload/$token'
    | '/api/form/$token'
    | '/api/internal/announcements'
    | '/api/internal/members'
    | '/api/prospeccion/agent'
    | '/artefacto/$id/raw'
    | '/coeditar/invitacion/$token'
    | '/oauth/$provider/callback'
    | '/setup/$provider/callback'
    | '/setup/$provider/connect'
    | '/setup/easybits/callback'
    | '/setup/easybits/connect'
    | '/api/collab/$docId/session-end'
    | '/api/collab/$docId/state'
    | '/api/hooks/sentry/$token'
    | '/api/p/c/$token'
    | '/api/p/o/$token'
    | '/api/p/u/$token'
    | '/api/whatsapp/connect/finish'
    | '/api/whatsapp/connect/start'
    | '/room/$slug_/transcripcion/$id'
    | '/api/hooks/whatsapp/$token/message'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtifactsRoute: typeof ArtifactsRoute
  BrandProbeRoute: typeof BrandProbeRoute
  BusyRoute: typeof BusyRoute
  CanvasDemoRoute: typeof CanvasDemoRoute
  CanvasProbeRoute: typeof CanvasProbeRoute
  DocProbeRoute: typeof DocProbeRoute
  FormsRoute: typeof FormsRoute
  LoginRoute: typeof LoginRoute
  MemoryRoute: typeof MemoryRoute
  SetupRoute: typeof SetupRouteWithChildren
  ApiAgentAssetRoute: typeof ApiAgentAssetRoute
  ApiBrandCssRoute: typeof ApiBrandCssRoute
  ApiBrandLogoRoute: typeof ApiBrandLogoRoute
  ApiEventStreamRoute: typeof ApiEventStreamRoute
  ApiManifestRoute: typeof ApiManifestRoute
  ApiStreamRoute: typeof ApiStreamRoute
  ApiTtsWarmRoute: typeof ApiTtsWarmRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiWarmRoute: typeof ApiWarmRoute
  ArtefactoIdRoute: typeof ArtefactoIdRouteWithChildren
  CSlugRoute: typeof CSlugRoute
  CoeditarSlugRoute: typeof CoeditarSlugRoute
  JoinTokenRoute: typeof JoinTokenRoute
  ProspeccionIdRoute: typeof ProspeccionIdRoute
  RoomSlugRoute: typeof RoomSlugRoute
  T3SplatRoute: typeof T3SplatRoute
  ProspeccionIndexRoute: typeof ProspeccionIndexRoute
  ApiArtifactStreamIdRoute: typeof ApiArtifactStreamIdRoute
  ApiAttachmentIdRoute: typeof ApiAttachmentIdRoute
  ApiBrandAssetSplatRoute: typeof ApiBrandAssetSplatRoute
  ApiConnectorsToolsRoute: typeof ApiConnectorsToolsRoute
  ApiDevDriveRoute: typeof ApiDevDriveRoute
  ApiDocCheckIdRoute: typeof ApiDocCheckIdRoute
  ApiDocDocxIdRoute: typeof ApiDocDocxIdRoute
  ApiDocPdfIdRoute: typeof ApiDocPdfIdRoute
  ApiDocTtsIdRoute: typeof ApiDocTtsIdRoute
  ApiDocXlsxIdRoute: typeof ApiDocXlsxIdRoute
  ApiFormDraftTokenRoute: typeof ApiFormDraftTokenRoute
  ApiFormFileIdRoute: typeof ApiFormFileIdRoute
  ApiFormUploadTokenRoute: typeof ApiFormUploadTokenRoute
  ApiFormTokenRoute: typeof ApiFormTokenRoute
  ApiInternalAnnouncementsRoute: typeof ApiInternalAnnouncementsRoute
  ApiInternalMembersRoute: typeof ApiInternalMembersRoute
  ApiProspeccionAgentRoute: typeof ApiProspeccionAgentRoute
  CoeditarInvitacionTokenRoute: typeof CoeditarInvitacionTokenRoute
  OauthProviderCallbackRoute: typeof OauthProviderCallbackRoute
  ApiCollabDocIdSessionEndRoute: typeof ApiCollabDocIdSessionEndRoute
  ApiCollabDocIdStateRoute: typeof ApiCollabDocIdStateRoute
  ApiHooksSentryTokenRoute: typeof ApiHooksSentryTokenRoute
  ApiPCTokenRoute: typeof ApiPCTokenRoute
  ApiPOTokenRoute: typeof ApiPOTokenRoute
  ApiPUTokenRoute: typeof ApiPUTokenRoute
  ApiWhatsappConnectFinishRoute: typeof ApiWhatsappConnectFinishRoute
  ApiWhatsappConnectStartRoute: typeof ApiWhatsappConnectStartRoute
  RoomSlugTranscripcionIdRoute: typeof RoomSlugTranscripcionIdRoute
  ApiHooksWhatsappTokenMessageRoute: typeof ApiHooksWhatsappTokenMessageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doc-probe': {
      id: '/doc-probe'
      path: '/doc-probe'
      fullPath: '/doc-probe'
      preLoaderRoute: typeof DocProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas-probe': {
      id: '/canvas-probe'
      path: '/canvas-probe'
      fullPath: '/canvas-probe'
      preLoaderRoute: typeof CanvasProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas-demo': {
      id: '/canvas-demo'
      path: '/canvas-demo'
      fullPath: '/canvas-demo'
      preLoaderRoute: typeof CanvasDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busy': {
      id: '/busy'
      path: '/busy'
      fullPath: '/busy'
      preLoaderRoute: typeof BusyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-probe': {
      id: '/brand-probe'
      path: '/brand-probe'
      fullPath: '/brand-probe'
      preLoaderRoute: typeof BrandProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof SetupRoute
    }
    '/prospeccion/': {
      id: '/prospeccion/'
      path: '/prospeccion'
      fullPath: '/prospeccion/'
      preLoaderRoute: typeof ProspeccionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t3/$': {
      id: '/t3/$'
      path: '/t3/$'
      fullPath: '/t3/$'
      preLoaderRoute: typeof T3SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$slug': {
      id: '/room/$slug'
      path: '/room/$slug'
      fullPath: '/room/$slug'
      preLoaderRoute: typeof RoomSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospeccion/$id': {
      id: '/prospeccion/$id'
      path: '/prospeccion/$id'
      fullPath: '/prospeccion/$id'
      preLoaderRoute: typeof ProspeccionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coeditar/$slug': {
      id: '/coeditar/$slug'
      path: '/coeditar/$slug'
      fullPath: '/coeditar/$slug'
      preLoaderRoute: typeof CoeditarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artefacto/$id': {
      id: '/artefacto/$id'
      path: '/artefacto/$id'
      fullPath: '/artefacto/$id'
      preLoaderRoute: typeof ArtefactoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/warm': {
      id: '/api/warm'
      path: '/api/warm'
      fullPath: '/api/warm'
      preLoaderRoute: typeof ApiWarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts-warm': {
      id: '/api/tts-warm'
      path: '/api/tts-warm'
      fullPath: '/api/tts-warm'
      preLoaderRoute: typeof ApiTtsWarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manifest': {
      id: '/api/manifest'
      path: '/api/manifest'
      fullPath: '/api/manifest'
      preLoaderRoute: typeof ApiManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/event-stream': {
      id: '/api/event-stream'
      path: '/api/event-stream'
      fullPath: '/api/event-stream'
      preLoaderRoute: typeof ApiEventStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand-logo': {
      id: '/api/brand-logo'
      path: '/api/brand-logo'
      fullPath: '/api/brand-logo'
      preLoaderRoute: typeof ApiBrandLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand-css': {
      id: '/api/brand-css'
      path: '/api/brand-css'
      fullPath: '/api/brand-css'
      preLoaderRoute: typeof ApiBrandCssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-asset': {
      id: '/api/agent-asset'
      path: '/api/agent-asset'
      fullPath: '/api/agent-asset'
      preLoaderRoute: typeof ApiAgentAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/easybits/connect': {
      id: '/setup/easybits/connect'
      path: '/easybits/connect'
      fullPath: '/setup/easybits/connect'
      preLoaderRoute: typeof SetupEasybitsConnectRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/easybits/callback': {
      id: '/setup/easybits/callback'
      path: '/easybits/callback'
      fullPath: '/setup/easybits/callback'
      preLoaderRoute: typeof SetupEasybitsCallbackRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/$provider/connect': {
      id: '/setup/$provider/connect'
      path: '/$provider/connect'
      fullPath: '/setup/$provider/connect'
      preLoaderRoute: typeof SetupProviderConnectRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/$provider/callback': {
      id: '/setup/$provider/callback'
      path: '/$provider/callback'
      fullPath: '/setup/$provider/callback'
      preLoaderRoute: typeof SetupProviderCallbackRouteImport
      parentRoute: typeof SetupRoute
    }
    '/oauth/$provider/callback': {
      id: '/oauth/$provider/callback'
      path: '/oauth/$provider/callback'
      fullPath: '/oauth/$provider/callback'
      preLoaderRoute: typeof OauthProviderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coeditar/invitacion/$token': {
      id: '/coeditar/invitacion/$token'
      path: '/coeditar/invitacion/$token'
      fullPath: '/coeditar/invitacion/$token'
      preLoaderRoute: typeof CoeditarInvitacionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artefacto/$id/raw': {
      id: '/artefacto/$id/raw'
      path: '/raw'
      fullPath: '/artefacto/$id/raw'
      preLoaderRoute: typeof ArtefactoIdRawRouteImport
      parentRoute: typeof ArtefactoIdRoute
    }
    '/api/prospeccion/agent': {
      id: '/api/prospeccion/agent'
      path: '/api/prospeccion/agent'
      fullPath: '/api/prospeccion/agent'
      preLoaderRoute: typeof ApiProspeccionAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/members': {
      id: '/api/internal/members'
      path: '/api/internal/members'
      fullPath: '/api/internal/members'
      preLoaderRoute: typeof ApiInternalMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/announcements': {
      id: '/api/internal/announcements'
      path: '/api/internal/announcements'
      fullPath: '/api/internal/announcements'
      preLoaderRoute: typeof ApiInternalAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/form/$token': {
      id: '/api/form/$token'
      path: '/api/form/$token'
      fullPath: '/api/form/$token'
      preLoaderRoute: typeof ApiFormTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/form-upload/$token': {
      id: '/api/form-upload/$token'
      path: '/api/form-upload/$token'
      fullPath: '/api/form-upload/$token'
      preLoaderRoute: typeof ApiFormUploadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/form-file/$id': {
      id: '/api/form-file/$id'
      path: '/api/form-file/$id'
      fullPath: '/api/form-file/$id'
      preLoaderRoute: typeof ApiFormFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/form-draft/$token': {
      id: '/api/form-draft/$token'
      path: '/api/form-draft/$token'
      fullPath: '/api/form-draft/$token'
      preLoaderRoute: typeof ApiFormDraftTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doc-xlsx/$id': {
      id: '/api/doc-xlsx/$id'
      path: '/api/doc-xlsx/$id'
      fullPath: '/api/doc-xlsx/$id'
      preLoaderRoute: typeof ApiDocXlsxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doc-tts/$id': {
      id: '/api/doc-tts/$id'
      path: '/api/doc-tts/$id'
      fullPath: '/api/doc-tts/$id'
      preLoaderRoute: typeof ApiDocTtsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doc-pdf/$id': {
      id: '/api/doc-pdf/$id'
      path: '/api/doc-pdf/$id'
      fullPath: '/api/doc-pdf/$id'
      preLoaderRoute: typeof ApiDocPdfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doc-docx/$id': {
      id: '/api/doc-docx/$id'
      path: '/api/doc-docx/$id'
      fullPath: '/api/doc-docx/$id'
      preLoaderRoute: typeof ApiDocDocxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doc-check/$id': {
      id: '/api/doc-check/$id'
      path: '/api/doc-check/$id'
      fullPath: '/api/doc-check/$id'
      preLoaderRoute: typeof ApiDocCheckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/drive': {
      id: '/api/dev/drive'
      path: '/api/dev/drive'
      fullPath: '/api/dev/drive'
      preLoaderRoute: typeof ApiDevDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/connectors/tools': {
      id: '/api/connectors/tools'
      path: '/api/connectors/tools'
      fullPath: '/api/connectors/tools'
      preLoaderRoute: typeof ApiConnectorsToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand-asset/$': {
      id: '/api/brand-asset/$'
      path: '/api/brand-asset/$'
      fullPath: '/api/brand-asset/$'
      preLoaderRoute: typeof ApiBrandAssetSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attachment/$id': {
      id: '/api/attachment/$id'
      path: '/api/attachment/$id'
      fullPath: '/api/attachment/$id'
      preLoaderRoute: typeof ApiAttachmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artifact-stream/$id': {
      id: '/api/artifact-stream/$id'
      path: '/api/artifact-stream/$id'
      fullPath: '/api/artifact-stream/$id'
      preLoaderRoute: typeof ApiArtifactStreamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$slug_/transcripcion/$id': {
      id: '/room/$slug_/transcripcion/$id'
      path: '/room/$slug/transcripcion/$id'
      fullPath: '/room/$slug/transcripcion/$id'
      preLoaderRoute: typeof RoomSlugTranscripcionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/connect/start': {
      id: '/api/whatsapp/connect/start'
      path: '/api/whatsapp/connect/start'
      fullPath: '/api/whatsapp/connect/start'
      preLoaderRoute: typeof ApiWhatsappConnectStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/connect/finish': {
      id: '/api/whatsapp/connect/finish'
      path: '/api/whatsapp/connect/finish'
      fullPath: '/api/whatsapp/connect/finish'
      preLoaderRoute: typeof ApiWhatsappConnectFinishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/p/u/$token': {
      id: '/api/p/u/$token'
      path: '/api/p/u/$token'
      fullPath: '/api/p/u/$token'
      preLoaderRoute: typeof ApiPUTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/p/o/$token': {
      id: '/api/p/o/$token'
      path: '/api/p/o/$token'
      fullPath: '/api/p/o/$token'
      preLoaderRoute: typeof ApiPOTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/p/c/$token': {
      id: '/api/p/c/$token'
      path: '/api/p/c/$token'
      fullPath: '/api/p/c/$token'
      preLoaderRoute: typeof ApiPCTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hooks/sentry/$token': {
      id: '/api/hooks/sentry/$token'
      path: '/api/hooks/sentry/$token'
      fullPath: '/api/hooks/sentry/$token'
      preLoaderRoute: typeof ApiHooksSentryTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/collab/$docId/state': {
      id: '/api/collab/$docId/state'
      path: '/api/collab/$docId/state'
      fullPath: '/api/collab/$docId/state'
      preLoaderRoute: typeof ApiCollabDocIdStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/collab/$docId/session-end': {
      id: '/api/collab/$docId/session-end'
      path: '/api/collab/$docId/session-end'
      fullPath: '/api/collab/$docId/session-end'
      preLoaderRoute: typeof ApiCollabDocIdSessionEndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hooks/whatsapp/$token/message': {
      id: '/api/hooks/whatsapp/$token/message'
      path: '/api/hooks/whatsapp/$token/message'
      fullPath: '/api/hooks/whatsapp/$token/message'
      preLoaderRoute: typeof ApiHooksWhatsappTokenMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SetupRouteChildren {
  SetupIndexRoute: typeof SetupIndexRoute
  SetupProviderCallbackRoute: typeof SetupProviderCallbackRoute
  SetupProviderConnectRoute: typeof SetupProviderConnectRoute
  SetupEasybitsCallbackRoute: typeof SetupEasybitsCallbackRoute
  SetupEasybitsConnectRoute: typeof SetupEasybitsConnectRoute
}

const SetupRouteChildren: SetupRouteChildren = {
  SetupIndexRoute: SetupIndexRoute,
  SetupProviderCallbackRoute: SetupProviderCallbackRoute,
  SetupProviderConnectRoute: SetupProviderConnectRoute,
  SetupEasybitsCallbackRoute: SetupEasybitsCallbackRoute,
  SetupEasybitsConnectRoute: SetupEasybitsConnectRoute,
}

const SetupRouteWithChildren = SetupRoute._addFileChildren(SetupRouteChildren)

interface ArtefactoIdRouteChildren {
  ArtefactoIdRawRoute: typeof ArtefactoIdRawRoute
}

const ArtefactoIdRouteChildren: ArtefactoIdRouteChildren = {
  ArtefactoIdRawRoute: ArtefactoIdRawRoute,
}

const ArtefactoIdRouteWithChildren = ArtefactoIdRoute._addFileChildren(
  ArtefactoIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtifactsRoute: ArtifactsRoute,
  BrandProbeRoute: BrandProbeRoute,
  BusyRoute: BusyRoute,
  CanvasDemoRoute: CanvasDemoRoute,
  CanvasProbeRoute: CanvasProbeRoute,
  DocProbeRoute: DocProbeRoute,
  FormsRoute: FormsRoute,
  LoginRoute: LoginRoute,
  MemoryRoute: MemoryRoute,
  SetupRoute: SetupRouteWithChildren,
  ApiAgentAssetRoute: ApiAgentAssetRoute,
  ApiBrandCssRoute: ApiBrandCssRoute,
  ApiBrandLogoRoute: ApiBrandLogoRoute,
  ApiEventStreamRoute: ApiEventStreamRoute,
  ApiManifestRoute: ApiManifestRoute,
  ApiStreamRoute: ApiStreamRoute,
  ApiTtsWarmRoute: ApiTtsWarmRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiWarmRoute: ApiWarmRoute,
  ArtefactoIdRoute: ArtefactoIdRouteWithChildren,
  CSlugRoute: CSlugRoute,
  CoeditarSlugRoute: CoeditarSlugRoute,
  JoinTokenRoute: JoinTokenRoute,
  ProspeccionIdRoute: ProspeccionIdRoute,
  RoomSlugRoute: RoomSlugRoute,
  T3SplatRoute: T3SplatRoute,
  ProspeccionIndexRoute: ProspeccionIndexRoute,
  ApiArtifactStreamIdRoute: ApiArtifactStreamIdRoute,
  ApiAttachmentIdRoute: ApiAttachmentIdRoute,
  ApiBrandAssetSplatRoute: ApiBrandAssetSplatRoute,
  ApiConnectorsToolsRoute: ApiConnectorsToolsRoute,
  ApiDevDriveRoute: ApiDevDriveRoute,
  ApiDocCheckIdRoute: ApiDocCheckIdRoute,
  ApiDocDocxIdRoute: ApiDocDocxIdRoute,
  ApiDocPdfIdRoute: ApiDocPdfIdRoute,
  ApiDocTtsIdRoute: ApiDocTtsIdRoute,
  ApiDocXlsxIdRoute: ApiDocXlsxIdRoute,
  ApiFormDraftTokenRoute: ApiFormDraftTokenRoute,
  ApiFormFileIdRoute: ApiFormFileIdRoute,
  ApiFormUploadTokenRoute: ApiFormUploadTokenRoute,
  ApiFormTokenRoute: ApiFormTokenRoute,
  ApiInternalAnnouncementsRoute: ApiInternalAnnouncementsRoute,
  ApiInternalMembersRoute: ApiInternalMembersRoute,
  ApiProspeccionAgentRoute: ApiProspeccionAgentRoute,
  CoeditarInvitacionTokenRoute: CoeditarInvitacionTokenRoute,
  OauthProviderCallbackRoute: OauthProviderCallbackRoute,
  ApiCollabDocIdSessionEndRoute: ApiCollabDocIdSessionEndRoute,
  ApiCollabDocIdStateRoute: ApiCollabDocIdStateRoute,
  ApiHooksSentryTokenRoute: ApiHooksSentryTokenRoute,
  ApiPCTokenRoute: ApiPCTokenRoute,
  ApiPOTokenRoute: ApiPOTokenRoute,
  ApiPUTokenRoute: ApiPUTokenRoute,
  ApiWhatsappConnectFinishRoute: ApiWhatsappConnectFinishRoute,
  ApiWhatsappConnectStartRoute: ApiWhatsappConnectStartRoute,
  RoomSlugTranscripcionIdRoute: RoomSlugTranscripcionIdRoute,
  ApiHooksWhatsappTokenMessageRoute: ApiHooksWhatsappTokenMessageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
