/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as SetupEasybitsConnectRouteImport } from './routes/setup.easybits.connect'
import { Route as SetupEasybitsCallbackRouteImport } from './routes/setup.easybits.callback'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupEasybitsConnectRoute = SetupEasybitsConnectRouteImport.update({
  id: '/easybits/connect',
  path: '/easybits/connect',
  getParentRoute: () => SetupRoute,
} as any)
const SetupEasybitsCallbackRoute = SetupEasybitsCallbackRouteImport.update({
  id: '/easybits/callback',
  path: '/easybits/callback',
  getParentRoute: () => SetupRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRouteWithChildren
  '/c/$slug': typeof CSlugRoute
  '/join/$token': typeof JoinTokenRoute
  '/setup/easybits/callback': typeof SetupEasybitsCallbackRoute
  '/setup/easybits/connect': typeof SetupEasybitsConnectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRouteWithChildren
  '/c/$slug': typeof CSlugRoute
  '/join/$token': typeof JoinTokenRoute
  '/setup/easybits/callback': typeof SetupEasybitsCallbackRoute
  '/setup/easybits/connect': typeof SetupEasybitsConnectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRouteWithChildren
  '/c/$slug': typeof CSlugRoute
  '/join/$token': typeof JoinTokenRoute
  '/setup/easybits/callback': typeof SetupEasybitsCallbackRoute
  '/setup/easybits/connect': typeof SetupEasybitsConnectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/setup'
    | '/c/$slug'
    | '/join/$token'
    | '/setup/easybits/callback'
    | '/setup/easybits/connect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/setup'
    | '/c/$slug'
    | '/join/$token'
    | '/setup/easybits/callback'
    | '/setup/easybits/connect'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/setup'
    | '/c/$slug'
    | '/join/$token'
    | '/setup/easybits/callback'
    | '/setup/easybits/connect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRouteWithChildren
  CSlugRoute: typeof CSlugRoute
  JoinTokenRoute: typeof JoinTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/easybits/connect': {
      id: '/setup/easybits/connect'
      path: '/easybits/connect'
      fullPath: '/setup/easybits/connect'
      preLoaderRoute: typeof SetupEasybitsConnectRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/easybits/callback': {
      id: '/setup/easybits/callback'
      path: '/easybits/callback'
      fullPath: '/setup/easybits/callback'
      preLoaderRoute: typeof SetupEasybitsCallbackRouteImport
      parentRoute: typeof SetupRoute
    }
  }
}

interface SetupRouteChildren {
  SetupEasybitsCallbackRoute: typeof SetupEasybitsCallbackRoute
  SetupEasybitsConnectRoute: typeof SetupEasybitsConnectRoute
}

const SetupRouteChildren: SetupRouteChildren = {
  SetupEasybitsCallbackRoute: SetupEasybitsCallbackRoute,
  SetupEasybitsConnectRoute: SetupEasybitsConnectRoute,
}

const SetupRouteWithChildren = SetupRoute._addFileChildren(SetupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRouteWithChildren,
  CSlugRoute: CSlugRoute,
  JoinTokenRoute: JoinTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
