/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as ApiStreamRouteImport } from './routes/api.stream'
import { Route as ApiAgentAssetRouteImport } from './routes/api.agent-asset'
import { Route as SetupEasybitsConnectRouteImport } from './routes/setup.easybits.connect'
import { Route as SetupEasybitsCallbackRouteImport } from './routes/setup.easybits.callback'
import { Route as ApiWebhookEasybitsRouteImport } from './routes/api.webhook.easybits'
import { Route as ApiDocDocxIdRouteImport } from './routes/api.doc-docx.$id'
import { Route as ApiDevDriveRouteImport } from './routes/api.dev.drive'
import { Route as ApiAttachmentIdRouteImport } from './routes/api.attachment.$id'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentAssetRoute = ApiAgentAssetRouteImport.update({
  id: '/api/agent-asset',
  path: '/api/agent-asset',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupEasybitsConnectRoute = SetupEasybitsConnectRouteImport.update({
  id: '/easybits/connect',
  path: '/easybits/connect',
  getParentRoute: () => SetupRoute,
} as any)
const SetupEasybitsCallbackRoute = SetupEasybitsCallbackRouteImport.update({
  id: '/easybits/callback',
  path: '/easybits/callback',
  getParentRoute: () => SetupRoute,
} as any)
const ApiWebhookEasybitsRoute = ApiWebhookEasybitsRouteImport.update({
  id: '/api/webhook/easybits',
  path: '/api/webhook/easybits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocDocxIdRoute = ApiDocDocxIdRouteImport.update({
  id: '/api/doc-docx/$id',
  path: '/api/doc-docx/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevDriveRoute = ApiDevDriveRouteImport.update({
  id: '/api/dev/drive',
  path: '/api/dev/drive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttachmentIdRoute = ApiAttachmentIdRouteImport.update({
  id: '/api/attachment/$id',
  path: '/api/attachment/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/forms': typeof FormsRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRouteWithChildren
  '/api/agent-asset': typeof ApiAgentAssetRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/upload': typeof ApiUploadRoute
  '/c/$slug': typeof CSlugRoute
  '/join/$token': typeof JoinTokenRoute
  '/api/attachment/$id': typeof ApiAttachmentIdRoute
  '/api/dev/drive': typeof ApiDevDriveRoute
  '/api/doc-docx/$id': typeof ApiDocDocxIdRoute
  '/api/webhook/easybits': typeof ApiWebhookEasybitsRoute
  '/setup/easybits/callback': typeof SetupEasybitsCallbackRoute
  '/setup/easybits/connect': typeof SetupEasybitsConnectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/forms': typeof FormsRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRouteWithChildren
  '/api/agent-asset': typeof ApiAgentAssetRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/upload': typeof ApiUploadRoute
  '/c/$slug': typeof CSlugRoute
  '/join/$token': typeof JoinTokenRoute
  '/api/attachment/$id': typeof ApiAttachmentIdRoute
  '/api/dev/drive': typeof ApiDevDriveRoute
  '/api/doc-docx/$id': typeof ApiDocDocxIdRoute
  '/api/webhook/easybits': typeof ApiWebhookEasybitsRoute
  '/setup/easybits/callback': typeof SetupEasybitsCallbackRoute
  '/setup/easybits/connect': typeof SetupEasybitsConnectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/forms': typeof FormsRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRouteWithChildren
  '/api/agent-asset': typeof ApiAgentAssetRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/upload': typeof ApiUploadRoute
  '/c/$slug': typeof CSlugRoute
  '/join/$token': typeof JoinTokenRoute
  '/api/attachment/$id': typeof ApiAttachmentIdRoute
  '/api/dev/drive': typeof ApiDevDriveRoute
  '/api/doc-docx/$id': typeof ApiDocDocxIdRoute
  '/api/webhook/easybits': typeof ApiWebhookEasybitsRoute
  '/setup/easybits/callback': typeof SetupEasybitsCallbackRoute
  '/setup/easybits/connect': typeof SetupEasybitsConnectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artifacts'
    | '/forms'
    | '/login'
    | '/setup'
    | '/api/agent-asset'
    | '/api/stream'
    | '/api/upload'
    | '/c/$slug'
    | '/join/$token'
    | '/api/attachment/$id'
    | '/api/dev/drive'
    | '/api/doc-docx/$id'
    | '/api/webhook/easybits'
    | '/setup/easybits/callback'
    | '/setup/easybits/connect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artifacts'
    | '/forms'
    | '/login'
    | '/setup'
    | '/api/agent-asset'
    | '/api/stream'
    | '/api/upload'
    | '/c/$slug'
    | '/join/$token'
    | '/api/attachment/$id'
    | '/api/dev/drive'
    | '/api/doc-docx/$id'
    | '/api/webhook/easybits'
    | '/setup/easybits/callback'
    | '/setup/easybits/connect'
  id:
    | '__root__'
    | '/'
    | '/artifacts'
    | '/forms'
    | '/login'
    | '/setup'
    | '/api/agent-asset'
    | '/api/stream'
    | '/api/upload'
    | '/c/$slug'
    | '/join/$token'
    | '/api/attachment/$id'
    | '/api/dev/drive'
    | '/api/doc-docx/$id'
    | '/api/webhook/easybits'
    | '/setup/easybits/callback'
    | '/setup/easybits/connect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtifactsRoute: typeof ArtifactsRoute
  FormsRoute: typeof FormsRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRouteWithChildren
  ApiAgentAssetRoute: typeof ApiAgentAssetRoute
  ApiStreamRoute: typeof ApiStreamRoute
  ApiUploadRoute: typeof ApiUploadRoute
  CSlugRoute: typeof CSlugRoute
  JoinTokenRoute: typeof JoinTokenRoute
  ApiAttachmentIdRoute: typeof ApiAttachmentIdRoute
  ApiDevDriveRoute: typeof ApiDevDriveRoute
  ApiDocDocxIdRoute: typeof ApiDocDocxIdRoute
  ApiWebhookEasybitsRoute: typeof ApiWebhookEasybitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-asset': {
      id: '/api/agent-asset'
      path: '/api/agent-asset'
      fullPath: '/api/agent-asset'
      preLoaderRoute: typeof ApiAgentAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/easybits/connect': {
      id: '/setup/easybits/connect'
      path: '/easybits/connect'
      fullPath: '/setup/easybits/connect'
      preLoaderRoute: typeof SetupEasybitsConnectRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/easybits/callback': {
      id: '/setup/easybits/callback'
      path: '/easybits/callback'
      fullPath: '/setup/easybits/callback'
      preLoaderRoute: typeof SetupEasybitsCallbackRouteImport
      parentRoute: typeof SetupRoute
    }
    '/api/webhook/easybits': {
      id: '/api/webhook/easybits'
      path: '/api/webhook/easybits'
      fullPath: '/api/webhook/easybits'
      preLoaderRoute: typeof ApiWebhookEasybitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/doc-docx/$id': {
      id: '/api/doc-docx/$id'
      path: '/api/doc-docx/$id'
      fullPath: '/api/doc-docx/$id'
      preLoaderRoute: typeof ApiDocDocxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/drive': {
      id: '/api/dev/drive'
      path: '/api/dev/drive'
      fullPath: '/api/dev/drive'
      preLoaderRoute: typeof ApiDevDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attachment/$id': {
      id: '/api/attachment/$id'
      path: '/api/attachment/$id'
      fullPath: '/api/attachment/$id'
      preLoaderRoute: typeof ApiAttachmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SetupRouteChildren {
  SetupEasybitsCallbackRoute: typeof SetupEasybitsCallbackRoute
  SetupEasybitsConnectRoute: typeof SetupEasybitsConnectRoute
}

const SetupRouteChildren: SetupRouteChildren = {
  SetupEasybitsCallbackRoute: SetupEasybitsCallbackRoute,
  SetupEasybitsConnectRoute: SetupEasybitsConnectRoute,
}

const SetupRouteWithChildren = SetupRoute._addFileChildren(SetupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtifactsRoute: ArtifactsRoute,
  FormsRoute: FormsRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRouteWithChildren,
  ApiAgentAssetRoute: ApiAgentAssetRoute,
  ApiStreamRoute: ApiStreamRoute,
  ApiUploadRoute: ApiUploadRoute,
  CSlugRoute: CSlugRoute,
  JoinTokenRoute: JoinTokenRoute,
  ApiAttachmentIdRoute: ApiAttachmentIdRoute,
  ApiDevDriveRoute: ApiDevDriveRoute,
  ApiDocDocxIdRoute: ApiDocDocxIdRoute,
  ApiWebhookEasybitsRoute: ApiWebhookEasybitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
